#!/usr/bin/env bash
# Bootstrap a per-group Postgres schema (Mode B — schema isolation).
#
# Clones the current `public` object set (tables, indexes, the vcon_tags_mv
# materialized view, triggers, and the search RPCs) into a new named schema in
# the SAME Supabase project, so a vCon MCP instance with SUPABASE_DB_SCHEMA=<schema>
# is fully isolated from other groups in that project.
#
# It works by dumping `public` schema-only with pg_dump, rewriting the schema
# name, and writing the result to a reviewable .sql file. By default it does NOT
# apply — review the generated SQL, then re-run with --apply (or psql it yourself).
#
# Why review first: cross-schema references (the `extensions` schema for pgvector
# etc., `auth`, `pg_catalog`) must stay pointing at their original schema, not be
# rewritten to <schema>. The rewrite below only retargets `public.`; verify the
# output before applying to a shared project.
#
# Usage:
#   scripts/bootstrap-schema.sh <schema> [--db-url URL] [--apply]
#
# Examples:
#   scripts/bootstrap-schema.sh sales
#       → writes sql/bootstrap-sales.sql (review it)
#   scripts/bootstrap-schema.sh sales --apply
#       → writes + applies it
#
# DB URL resolution (first match wins):
#   1. --db-url argument
#   2. $SUPABASE_DB_URL
#   3. local default: postgresql://postgres:postgres@127.0.0.1:54322/postgres
#
# Requires: pg_dump and psql on PATH.
#
# After applying, remember to ADD <schema> to PostgREST exposed schemas
# (Dashboard → API → Exposed schemas, or [api] schemas in supabase/config.toml)
# or supabase-js will not be able to reach it.

set -euo pipefail

SCHEMA="${1:-}"
if [[ -z "$SCHEMA" ]]; then
  echo "Usage: $0 <schema> [--db-url URL] [--apply]" >&2
  exit 2
fi
shift || true

DB_URL="${SUPABASE_DB_URL:-postgresql://postgres:postgres@127.0.0.1:54322/postgres}"
APPLY=false
while [[ $# -gt 0 ]]; do
  case "$1" in
    --db-url) DB_URL="$2"; shift 2 ;;
    --apply)  APPLY=true; shift ;;
    *) echo "Unknown argument: $1" >&2; exit 2 ;;
  esac
done

# Reject reserved / unsafe schema names.
if [[ "$SCHEMA" =~ [^a-zA-Z0-9_] || "$SCHEMA" == "public" || "$SCHEMA" == "extensions" || "$SCHEMA" == "auth" ]]; then
  echo "Refusing schema name '$SCHEMA' (use a simple identifier; not public/extensions/auth)." >&2
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT_DIR="$ROOT/sql"
OUT_FILE="$OUT_DIR/bootstrap-$SCHEMA.sql"
mkdir -p "$OUT_DIR"

echo "Dumping public schema from $DB_URL ..." >&2
DUMP="$(pg_dump --schema-only --no-owner --no-privileges -n public -d "$DB_URL")"

# Rewrite public -> <schema>. Retarget only `public.` qualified refs and the
# schema declarations; leave extensions/auth/pg_catalog untouched.
echo "Rewriting public -> $SCHEMA ..." >&2
{
  echo "-- Generated by scripts/bootstrap-schema.sh for schema '$SCHEMA'."
  echo "-- REVIEW cross-schema references (extensions/auth) before applying."
  echo "CREATE SCHEMA IF NOT EXISTS \"$SCHEMA\";"
  echo "SET search_path TO \"$SCHEMA\", extensions, public;"
  echo
  printf '%s\n' "$DUMP" \
    | sed -E "s/\bpublic\./${SCHEMA}./g" \
    | sed -E "s/CREATE SCHEMA public;//g" \
    | sed -E "s/SET search_path = public/SET search_path = ${SCHEMA}/g"
} > "$OUT_FILE"

echo "Wrote $OUT_FILE" >&2

if [[ "$APPLY" == true ]]; then
  echo "Applying $OUT_FILE to $DB_URL ..." >&2
  psql "$DB_URL" -v ON_ERROR_STOP=1 -f "$OUT_FILE"
  echo "Applied. Don't forget to expose '$SCHEMA' to PostgREST." >&2
else
  echo "Dry run (no --apply). Review the SQL, then re-run with --apply or:" >&2
  echo "  psql \"$DB_URL\" -v ON_ERROR_STOP=1 -f $OUT_FILE" >&2
fi
