-- Reconcile vCon child-table foreign keys to reference vcons(uuid).
--
-- Background: every child table (analysis, attachments, dialog, parties,
-- groups, vcon_embeddings, embedding_queue, s3_sync_tracking) historically
-- declared its `vcon_id` foreign key as `REFERENCES vcons(id)` in source
-- migrations. The live database was migrated at some point — out of band —
-- so that every one of those FKs now references `vcons(uuid)` instead, and
-- the data in those `vcon_id` columns contains values from `vcons.uuid`,
-- not `vcons.id`. The source repository has been silently diverged from
-- production for an unknown window.
--
-- The symptom we just caught was the `enqueue_embedding` trigger inserting
-- `NEW.id` into `embedding_queue.vcon_id` whose FK had been flipped to
-- `vcons(uuid)` without a corresponding trigger update — every INSERT into
-- `vcons` rolled back for ~6 hours on 2026-05-27.
--
-- This migration is the source-side reconciliation. It walks every FK that
-- targets `vcons.id` and re-points it at `vcons.uuid`. It's idempotent —
-- on a database that's already converted (every live system) it's a no-op.
-- It also drops the duplicate `fk_vcon_uuid` constraint on `s3_sync_tracking`
-- (a copy of `s3_sync_tracking_vcon_id_fkey` on the same column).

-- 1. Re-point every vcon-child-table FK from vcons.id → vcons.uuid.
DO $$
DECLARE
    fk RECORD;
    referenced_attr_name TEXT;
BEGIN
    FOR fk IN
        SELECT c.conname,
               c.conrelid::regclass AS tbl,
               pa.attname AS referenced_col
        FROM pg_constraint c
        JOIN pg_attribute pa
          ON pa.attrelid = c.confrelid
         AND pa.attnum  = c.confkey[1]
        WHERE c.confrelid = 'vcons'::regclass
          AND c.contype   = 'f'
          AND pa.attname  = 'id'
    LOOP
        RAISE NOTICE 'Re-pointing % on % from vcons.id → vcons.uuid',
                     fk.conname, fk.tbl;
        EXECUTE format(
            'ALTER TABLE %s DROP CONSTRAINT %I',
            fk.tbl, fk.conname
        );
        EXECUTE format(
            'ALTER TABLE %s ADD CONSTRAINT %I '
            'FOREIGN KEY (vcon_id) REFERENCES vcons(uuid) ON DELETE CASCADE',
            fk.tbl, fk.conname
        );
    END LOOP;
END $$;

-- 2. Drop the duplicate FK on s3_sync_tracking.
--    `fk_vcon_uuid` and `s3_sync_tracking_vcon_id_fkey` both live on
--    s3_sync_tracking.vcon_id with identical definitions in production.
--    Keep the autogenerated-style name; drop the duplicate.
ALTER TABLE s3_sync_tracking DROP CONSTRAINT IF EXISTS fk_vcon_uuid;
